training_pipeline_config:
  pipeline_name: Artifact
  artifact_dir: artifact

data_ingestion_config:
  data_base: Machine_Failure
  collection_name: Data
  data_ingestion: data_ingestion
  raw_data_dir: raw_data
  ingested_dir: ingested_Data
  ingested_train_dir: Train
  ingested_test_dir: Test

data_validation_config:
  data_validation_dir: data_validation
  validated_data: validated_data
  Train_data: Train
  Test_data: Test

data_transformation_config:
  data_transformation_dir: data_transformation
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl
  feature_eng_file: fea_eng.pkl

model_trainer_config:
  model_training: model_training 
  model_object: model.pkl
  model_report: report.yaml

model_eval_config:
  model_eval_dir: model_evaluation
  model_eval_report: model_report.yaml

saved_model_config:
  directory: Saved_model
  model_object: model.pkl
  report : report.yaml